# Generated by Django 3.0.6 on 2020-05-22 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emp', models.CharField(max_length=250, verbose_name='Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('insc_estadual', models.CharField(blank=True, max_length=9, verbose_name='Inscrição Estadual')),
                ('telefone_emp', models.CharField(max_length=8, verbose_name='Telefone')),
                ('rua', models.CharField(max_length=500, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('status', models.BooleanField(default=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ramais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramal', models.CharField(max_length=4, verbose_name='Ramal')),
                ('nome_resp', models.CharField(max_length=30, verbose_name='Nome do Responsavél')),
                ('email', models.EmailField(max_length=60)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('empresa_ramais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Empresas', verbose_name='Empresa')),
                ('setor_ramais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Setores', verbose_name='Setor')),
            ],
            options={
                'db_table': 'ramais',
            },
        ),
    ]
