# Generated by Django 3.0.6 on 2020-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=21, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefone_emp',
            field=models.CharField(max_length=13, verbose_name='Telefone'),
        ),
    ]
