# Generated by Django 3.0.6 on 2020-05-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200521_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nome',
        ),
    ]
