# Generated by Django 3.0.6 on 2020-05-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuarios_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
