# Generated by Django 3.0.6 on 2020-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='insc_estadual',
            field=models.CharField(blank=True, max_length=13, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='nome_resp',
            field=models.CharField(max_length=30, verbose_name='Responsavél'),
        ),
    ]
