# Generated by Django 3.0.6 on 2020-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200523_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='empresa_ramais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Empresas'),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='setor_ramais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Setores'),
        ),
    ]
