# Generated by Django 3.0.6 on 2020-06-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200606_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='empresa_ramais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Empresas', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='setor_ramais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Setores', verbose_name='Setor'),
        ),
    ]
