# Generated by Django 6.1.1 on 2026-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_auto_20200606_1858"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresas",
            options={
                "ordering": ["nome_emp"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterModelOptions(
            name="ramais",
            options={
                "ordering": ["ramal"],
                "verbose_name": "Ramal",
                "verbose_name_plural": "Ramais",
            },
        ),
        migrations.AlterModelOptions(
            name="setores",
            options={
                "ordering": ["setor"],
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.AlterField(
            model_name="empresas",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ramais",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="ramais",
            name="email",
            field=models.EmailField(max_length=60, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="ramais",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ramais",
            name="nome_resp",
            field=models.CharField(max_length=30, verbose_name="Responsável"),
        ),
        migrations.AlterField(
            model_name="setores",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="setores",
            name="setor",
            field=models.CharField(max_length=150, unique=True, verbose_name="Setor"),
        ),
    ]
